apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-k8s
  template:
    metadata:
      labels:
        app: helloworld-k8s
    spec:
      containers:
        - name: helloworld-k8s-container
          image: berkayersoyy/helloworld-k8s
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000